version '3.8'
services:
    server:
        image: fabiomen10/quadl:latest
        container_name: quadl
        ports:
            - "8080:8080"
    db:
        image: linuxserver/mariadb:alpine
        container_name: mariadb
        ports:
            - "3306:3306"